/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wiki.parser.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test
    void testGetMessage() {

    }
}
