/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wiki.parser.java-library-conventions")
}

dependencies {
    annotationProcessor(project(":annotation"))

    implementation(project(":annotation"))

    //Used to remove markup tags from wikipedia page text
    implementation("org.wikiclean:wikiclean:1.2")

    //used to decompress bz2 format (can decompress gzip, bz2, 7z, zip etc)
    //api means this dependency is exposed to modules using this one
    api("org.apache.commons:commons-compress:1.27.1")
}
