/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wiki.parser.java-library-conventions")
}

dependencies {
    annotationProcessor(project(":annotation"))

    implementation(project(":annotation"))
    implementation("org.wikiclean:wikiclean:1.2")
}
