import org.springframework.boot.gradle.tasks.run.BootRun

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wiki.parser.spring-application-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation(project(":database"))

    implementation("org.springframework.boot:spring-boot-starter-web")

    runtimeOnly("org.postgresql:postgresql")

    testImplementation(testFixtures(project(":database")))
}

tasks.withType<BootRun> {
    systemProperties = System.getProperties().map { it.key.toString() to it.value.toString() }.toMap()
}


application {
    // Define the main class for the application.
    mainClass.set("wiki.parser.app.App")
}
