/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wiki.parser.spring-application-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation(project(":database"))

    testImplementation(testFixtures(project(":database")))
}

application {
    // Define the main class for the application.
    mainClass.set("wiki.parser.app.App")
}
