/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("wiki.parser.java-library-conventions")
    id("wiki.parser.spring-common-conventions")
}

dependencies {

    implementation(project(":core"))

    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    //validation
    implementation("org.springframework.boot:spring-boot-starter-validation")

    //liquibase
    implementation("org.liquibase:liquibase-core")

    testImplementation("org.testcontainers:postgresql:1.20.1")
    testRuntimeOnly("org.postgresql:postgresql")

}
