import java.io.FileInputStream
import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java

    //produces coverage information
    id("jacoco")
}

val props = Properties().apply {
    load(FileInputStream(file("../gradle.properties")))
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    compileOnly("org.projectlombok:lombok:${props.getProperty("lombokVersion")}")
    annotationProcessor("org.projectlombok:lombok:${props.getProperty("lombokVersion")}")


    testCompileOnly("org.projectlombok:lombok:${props.getProperty("lombokVersion")}")
    testAnnotationProcessor("org.projectlombok:lombok:${props.getProperty("lombokVersion")}")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test) // tests are required to run before generating the report
            reports {
                xml.required = false
                csv.required = false
            }
}
