import java.io.FileInputStream
import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

val props = Properties().apply {
    load(FileInputStream(file("../gradle.properties")))
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("io.spring.gradle:dependency-management-plugin:1.1.6")
    //Defines the spring version
    implementation("org.springframework.boot:spring-boot-gradle-plugin:${props.getProperty("springVersion")}")
}
